n1 = input('Digite algo:')
print('O tipo primitivo desse valor é {}'.format(type(n1)))
print('Só tem espaços? {}'.format(n1.isspace()))
print('É Numero? {}'.format(n1.isnumeric()))
print('É alfabético? {}'.format(n1.isalpha()))
print('É alfa numérico? {}'.format(n1.isalnum()))
print('Está em maiusculas? {}'.format(n1.isupper()))
print('Está em minusculas? {}'.format(n1.islower()))
print('Está capitalizada? {}'.format(n1.istitle()))